import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import React from "react";
import NavigationBar from "@/components/navBar/NavigationBar";
import CalenderElement from "@/components/CalenderElement";
import MainContentTop from "@/components/mainContentTop/MainContentTop";
import MainContentBottom from "@/components/mainContentBottom/MainContentBottom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Samy´s Finace Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="full-height">
      <body className={`{inter.className} full-height`}>
      <div className="container">
        <ThemeProvider attribute="class" defaultTheme="dark">
            <NavigationBar />
            <div className="flex">
            <CalenderElement />
            <MainContentTop />
            </div>
            <div className="flex">
            <MainContentBottom />
            </div>
            {children}
        </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
