import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import React from "react";
import NavigationBar from "@/components/navBar/NavigationBar";
import CalenderElement from "@/components/CalenderElement";
import MainContentTop from "@/components/mainContentTop/MainContentTop";
import MainContentBottom from "@/components/mainContentBottom/MainContentBottom";
import { Drawer } from "@/components/ui/drawer";
import SandwichMenu from "@/components/navBar/SandwichMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Samy´s Finace Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`{inter.className} `}>
        <div className="min-h-screen flex flex-col">
          <ThemeProvider attribute="class" defaultTheme="dark">
            <SandwichMenu />
            <NavigationBar />
            <div className="flex-1 flex">
              <CalenderElement />
              <div className="flex flex-col flex-1">
                <MainContentTop />
                <MainContentBottom />
              </div>
            </div>
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
